State.create(name: "AGUASCALIENTES", code: "AGS")
State.create(name: "BAJA CALIFORNIA", code: "BC",)
State.create(name: "BAJA CALIFORNIA SUR", code: "BCS")
State.create(name: "CHIHUAHUA", code: "CHI")
State.create(name: "CHIAPAS", code: "CHS")
State.create(name: "CAMPECHE", code: "CMP")
State.create(name: "CIUDAD DE MEXICO", code: "CMX")
State.create(name: "COAHUILA", code: "COA")
State.create(name: "COLIMA", code: "COL")
State.create(name: "DURANGO", code: "DGO")
State.create(name: "GUERRERO", code: "GRO")
State.create(name: "GUANAJUATO", code: "GTO")
State.create(name: "HIDALGO", code: "HGO")
State.create(name: "JALISCO", code: "JAL")
State.create(name: "MICHOACAN", code: "MCH")
State.create(name: "ESTADO DE MEXICO", code: "MEX")
State.create(name: "MORELOS", code: "MOR")
State.create(name: "NAYARIT", code: "NAY")
State.create(name: "NUEVO LEON", code: "NL",)
State.create(name: "OAXACA", code: "OAX")
State.create(name: "PUEBLA", code: "PUE")
State.create(name: "QUINTANA ROO", code: "QR",)
State.create(name: "QUERETARO", code: "QRO")
State.create(name: "SINALOA", code: "SIN")
State.create(name: "SAN LUIS POTOSI", code: "SLP")
State.create(name: "SONORA", code: "SON")
State.create(name: "TABASCO", code: "TAB")
State.create(name: "TLAXCALA", code: "TLX")
State.create(name: "TAMAULIPAS", code: "TMS")
State.create(name: "VERACRUZ", code: "VER")
State.create(name: "YUCATAN", code: "YUC")
State.create(name: "ZACATECAS", code: "ZAC");
